[package]
name = "loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deep_world_core = { path = "../core" }
serde_json = "1.0"
serde_yaml = "0.9"
